server:
  port: 8084

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: catalogFinal
      port: 27017
      host: mongodbCatalog
