server:
  port: 8088

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: catalogFinal
      port: 27018
      host: mongodbCatalog
