server:
  port: 8080
  
spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8083/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

info:
  app:
    name: $(spring.application.name)
    version: 1.0.0
    description: API Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
