server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/backendFinal
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
